# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from tkinter import filedialog
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib import pyplot as plt
from matplotlib.backend_bases import FigureCanvasBase
from matplotlib.figure import Figure

from file_operations import FileOperations
import copy
from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib import pyplot as plt
import numpy as np
from visualization import Visualization

from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):

    def __init__(self):
        self.file_operations = FileOperations()
        self.visualization = Visualization()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 797)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.import_btn = QtWidgets.QPushButton(self.centralwidget)
        self.import_btn.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.import_btn.setObjectName("import_btn")
        self.export_btn = QtWidgets.QPushButton(self.centralwidget)
        self.export_btn.setGeometry(QtCore.QRect(80, 0, 75, 23))
        self.export_btn.setObjectName("export_btn")
        self.undo_tool = QtWidgets.QToolButton(self.centralwidget)
        self.undo_tool.setGeometry(QtCore.QRect(260, 0, 23, 20))
        self.undo_tool.setObjectName("undo_tool")
        self.redo_tool = QtWidgets.QToolButton(self.centralwidget)
        self.redo_tool.setGeometry(QtCore.QRect(290, 0, 23, 20))
        self.redo_tool.setObjectName("redo_tool")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(40, 100, 261, 631))
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBox.setWhatsThis("")
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setObjectName("toolBox")
        self.view_ctrl = QtWidgets.QWidget()
        self.view_ctrl.setGeometry(QtCore.QRect(0, 0, 261, 547))
        self.view_ctrl.setObjectName("view_ctrl")
        self.label_2 = QtWidgets.QLabel(self.view_ctrl)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.XRange_minTB = QtWidgets.QLineEdit(self.view_ctrl)
        self.XRange_minTB.setGeometry(QtCore.QRect(40, 90, 51, 20))
        self.XRange_minTB.setObjectName("XRange_minTB")
        self.label_3 = QtWidgets.QLabel(self.view_ctrl)
        self.label_3.setGeometry(QtCore.QRect(10, 250, 47, 14))
        self.label_3.setObjectName("label_3")
        self.contrastTB = QtWidgets.QLineEdit(self.view_ctrl)
        self.contrastTB.setGeometry(QtCore.QRect(60, 250, 51, 20))
        self.contrastTB.setObjectName("contrastTB")
        self.gridBtn = QtWidgets.QPushButton(self.view_ctrl)
        self.gridBtn.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.gridBtn.setObjectName("gridBtn")
        self.label_4 = QtWidgets.QLabel(self.view_ctrl)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.label_4.setObjectName("label_4")
        self.fviewBtn = QtWidgets.QPushButton(self.view_ctrl)
        self.fviewBtn.setGeometry(QtCore.QRect(130, 10, 75, 23))
        self.fviewBtn.setObjectName("fviewBtn")
        self.label_5 = QtWidgets.QLabel(self.view_ctrl)
        self.label_5.setGeometry(QtCore.QRect(10, 210, 71, 16))
        self.label_5.setObjectName("label_5")
        self.aspect_ratioTB = QtWidgets.QLineEdit(self.view_ctrl)
        self.aspect_ratioTB.setGeometry(QtCore.QRect(90, 210, 113, 20))
        self.aspect_ratioTB.setObjectName("aspect_ratioTB")
        self.label_25 = QtWidgets.QLabel(self.view_ctrl)
        self.label_25.setGeometry(QtCore.QRect(10, 90, 21, 16))
        self.label_25.setObjectName("label_25")
        self.XRange_maxTB = QtWidgets.QLineEdit(self.view_ctrl)
        self.XRange_maxTB.setGeometry(QtCore.QRect(140, 90, 51, 20))
        self.XRange_maxTB.setText("")
        self.XRange_maxTB.setObjectName("XRange_maxTB")
        self.label_26 = QtWidgets.QLabel(self.view_ctrl)
        self.label_26.setGeometry(QtCore.QRect(110, 90, 21, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.view_ctrl)
        self.label_27.setGeometry(QtCore.QRect(110, 150, 21, 16))
        self.label_27.setObjectName("label_27")
        self.YRange_maxTB_ = QtWidgets.QLineEdit(self.view_ctrl)
        self.YRange_maxTB_.setGeometry(QtCore.QRect(140, 150, 51, 20))
        self.YRange_maxTB_.setText("")
        self.YRange_maxTB_.setObjectName("YRange_maxTB_")
        self.YRange_minTB = QtWidgets.QLineEdit(self.view_ctrl)
        self.YRange_minTB.setGeometry(QtCore.QRect(40, 150, 51, 20))
        self.YRange_minTB.setObjectName("YRange_minTB")
        self.label_28 = QtWidgets.QLabel(self.view_ctrl)
        self.label_28.setGeometry(QtCore.QRect(10, 150, 21, 16))
        self.label_28.setObjectName("label_28")
        self.contrastCB = QtWidgets.QComboBox(self.view_ctrl)
        self.contrastCB.setGeometry(QtCore.QRect(140, 250, 60, 22))
        self.contrastCB.setObjectName("contrastCB")
        self.toolBox.addItem(self.view_ctrl, "")
        self.velo_ctrl = QtWidgets.QWidget()
        self.velo_ctrl.setGeometry(QtCore.QRect(0, 0, 261, 547))
        self.velo_ctrl.setObjectName("velo_ctrl")
        self.label_7 = QtWidgets.QLabel(self.velo_ctrl)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.velo_ctrl)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 120, 113, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_8 = QtWidgets.QLabel(self.velo_ctrl)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.velo_ctrl)
        self.lineEdit_8.setGeometry(QtCore.QRect(130, 90, 113, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_9 = QtWidgets.QLabel(self.velo_ctrl)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_9.setObjectName("label_9")
        self.veloTB = QtWidgets.QLineEdit(self.velo_ctrl)
        self.veloTB.setGeometry(QtCore.QRect(130, 10, 113, 20))
        self.veloTB.setObjectName("veloTB")
        self.antenBtn = QtWidgets.QPushButton(self.velo_ctrl)
        self.antenBtn.setGeometry(QtCore.QRect(40, 50, 151, 23))
        self.antenBtn.setObjectName("antenBtn")
        self.traceBtn = QtWidgets.QPushButton(self.velo_ctrl)
        self.traceBtn.setGeometry(QtCore.QRect(40, 160, 151, 23))
        self.traceBtn.setObjectName("traceBtn")
        self.toolBox.addItem(self.velo_ctrl, "")
        self.prof_ctrl = QtWidgets.QWidget()
        self.prof_ctrl.setGeometry(QtCore.QRect(0, 0, 261, 547))
        self.prof_ctrl.setObjectName("prof_ctrl")
        self.label_10 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.prof_ctrl)
        self.lineEdit_10.setGeometry(QtCore.QRect(120, 10, 113, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_11 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label_11.setObjectName("label_11")
        self.zTimeTB = QtWidgets.QLineEdit(self.prof_ctrl)
        self.zTimeTB.setGeometry(QtCore.QRect(120, 40, 113, 20))
        self.zTimeTB.setObjectName("zTimeTB")
        self.label_12 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.prof_ctrl)
        self.lineEdit_12.setGeometry(QtCore.QRect(120, 70, 113, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_13 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_13.setGeometry(QtCore.QRect(10, 100, 71, 16))
        self.label_13.setObjectName("label_13")
        self.truncTB = QtWidgets.QLineEdit(self.prof_ctrl)
        self.truncTB.setGeometry(QtCore.QRect(120, 100, 113, 20))
        self.truncTB.setObjectName("truncTB")
        self.label_14 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_14.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.label_14.setObjectName("label_14")
        self.XcutTB = QtWidgets.QLineEdit(self.prof_ctrl)
        self.XcutTB.setGeometry(QtCore.QRect(40, 160, 61, 20))
        self.XcutTB.setObjectName("XcutTB")
        self.label_15 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_15.setGeometry(QtCore.QRect(10, 190, 71, 16))
        self.label_15.setObjectName("label_15")
        self.dewowTB = QtWidgets.QLineEdit(self.prof_ctrl)
        self.dewowTB.setGeometry(QtCore.QRect(120, 190, 113, 20))
        self.dewowTB.setObjectName("dewowTB")
        self.label_16 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_16.setGeometry(QtCore.QRect(10, 220, 111, 16))
        self.label_16.setObjectName("label_16")
        self.rmtTB = QtWidgets.QLineEdit(self.prof_ctrl)
        self.rmtTB.setGeometry(QtCore.QRect(120, 220, 113, 20))
        self.rmtTB.setText("")
        self.rmtTB.setObjectName("rmtTB")
        self.label_18 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_18.setGeometry(QtCore.QRect(10, 250, 71, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_19.setGeometry(QtCore.QRect(10, 330, 71, 16))
        self.label_19.setObjectName("label_19")
        self.t_powTB = QtWidgets.QLineEdit(self.prof_ctrl)
        self.t_powTB.setGeometry(QtCore.QRect(120, 330, 113, 20))
        self.t_powTB.setObjectName("t_powTB")
        self.label_20 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_20.setGeometry(QtCore.QRect(20, 360, 71, 16))
        self.label_20.setObjectName("label_20")
        self.acgTB = QtWidgets.QLineEdit(self.prof_ctrl)
        self.acgTB.setGeometry(QtCore.QRect(120, 360, 113, 20))
        self.acgTB.setObjectName("acgTB")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.prof_ctrl)
        self.lineEdit_21.setGeometry(QtCore.QRect(50, 420, 113, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_21 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_21.setGeometry(QtCore.QRect(10, 390, 71, 16))
        self.label_21.setObjectName("label_21")
        self.label_29 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_29.setGeometry(QtCore.QRect(0, 160, 41, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_30.setGeometry(QtCore.QRect(120, 160, 41, 16))
        self.label_30.setObjectName("label_30")
        self.YcutTB = QtWidgets.QLineEdit(self.prof_ctrl)
        self.YcutTB.setGeometry(QtCore.QRect(160, 160, 61, 20))
        self.YcutTB.setObjectName("YcutTB")
        self.label_31 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_31.setGeometry(QtCore.QRect(20, 270, 81, 16))
        self.label_31.setObjectName("label_31")
        self.t_numTB = QtWidgets.QLineEdit(self.prof_ctrl)
        self.t_numTB.setGeometry(QtCore.QRect(30, 290, 61, 20))
        self.t_numTB.setObjectName("t_numTB")
        self.label_32 = QtWidgets.QLabel(self.prof_ctrl)
        self.label_32.setGeometry(QtCore.QRect(130, 270, 81, 16))
        self.label_32.setObjectName("label_32")
        self.cpy_numTB = QtWidgets.QLineEdit(self.prof_ctrl)
        self.cpy_numTB.setGeometry(QtCore.QRect(130, 290, 61, 20))
        self.cpy_numTB.setObjectName("cpy_numTB")
        self.toolBox.addItem(self.prof_ctrl, "")
        self.save_tool = QtWidgets.QToolButton(self.centralwidget)
        self.save_tool.setGeometry(QtCore.QRect(160, 0, 23, 20))
        self.save_tool.setObjectName("save_tool")
        self.refresh_tool = QtWidgets.QToolButton(self.centralwidget)
        self.refresh_tool.setGeometry(QtCore.QRect(330, 0, 23, 20))
        self.refresh_tool.setObjectName("refresh_tool")
        self.display_frame = QtWidgets.QFrame(self.centralwidget)
        self.display_frame.setGeometry(QtCore.QRect(309, 29, 791, 731))
        self.display_frame.setAutoFillBackground(False)
        self.display_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.display_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.display_frame.setLineWidth(5)
        self.display_frame.setObjectName("display_frame")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 30, 31, 16))
        self.label.setObjectName("label")
        self.start_tool = QtWidgets.QToolButton(self.centralwidget)
        self.start_tool.setGeometry(QtCore.QRect(370, 0, 23, 20))
        self.start_tool.setObjectName("start_tool")
        self.stop_tool = QtWidgets.QToolButton(self.centralwidget)
        self.stop_tool.setGeometry(QtCore.QRect(410, 0, 23, 20))
        self.stop_tool.setObjectName("stop_tool")
        self.print_tool = QtWidgets.QToolButton(self.centralwidget)
        self.print_tool.setGeometry(QtCore.QRect(190, 0, 23, 20))
        self.print_tool.setObjectName("print_tool")
        self.script_tool = QtWidgets.QToolButton(self.centralwidget)
        self.script_tool.setGeometry(QtCore.QRect(220, 0, 23, 20))
        self.script_tool.setObjectName("script_tool")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        #set x,y range
        self.XRange_minTB.editingFinished.connect(self.set_x_range)
        self.XRange_maxTB.editingFinished.connect(self.set_x_range)
        self.YRange_maxTB_.editingFinished.connect(self.set_y_range)
        self.YRange_minTB.editingFinished.connect(self.set_y_range)
        

        self.display_frame.setLayout(QtWidgets.QVBoxLayout())
        # Connect the clicked signal of the import button to the import_file method of file_operations
        self.import_btn.clicked.connect(self.import_file)
        self.export_btn.clicked.connect(self.export_file)
        
    def set_x_range(self):
        try:
            xlow = float(self.XRange_minTB.text())
            xhigh = float(self.XRange_maxTB.text())
            self.visualization.setXrng(xlow, xhigh)
            self.update_display_frame()
        except ValueError as e:
            print(e)
            QMessageBox.warning(None, "Error", "Invalid X range. Please enter valid numbers.")
        except Exception as e:
            QMessageBox.warning(None, "Error", f"An error occurred: {str(e)}")

    def set_y_range(self):
        try:
            ylow = float(self.YRange_minTB.text())
            yhigh = float(self.YRange_maxTB_.text())
            self.visualization.setYrng(ylow, yhigh)
            self.update_display_frame()
        except ValueError:
            QMessageBox.warning(None, "Error", "Invalid Y range. Please enter valid numbers.")
        except Exception as e:
            QMessageBox.warning(None, "Error", f"An error occurred: {str(e)}")

    def update_display_frame(self):
        # Clear any existing widgets in the display_frame layout
        for i in reversed(range(self.display_frame.layout().count())):
            widget = self.display_frame.layout().itemAt(i).widget()
            if widget:
                widget.setParent(None)

        # Get the canvas object returned by displayDataInViewingWindow
        canvas = self.file_operations.displayDataInViewingWindow()

        # Add canvas to the layout of display_frame
        self.display_frame.layout().addWidget(canvas)

    def import_file(self):
        try:
            options = QFileDialog.Options()
            options |= QFileDialog.DontUseNativeDialog
            filename, _ = QFileDialog.getOpenFileName(
                None, "Select File to Import", "", "Supported Files (*.dt1 *.DT1 *.hd *.HD *.DZT *.dat *.GPRhdr *.rad *.rd3 *.rd7 *.gpr)", options=options)

            if filename:
                print("Attempting to import file:", filename)
                
                self.file_operations.importdata(filename)

                # Clear any existing widgets in the display_frame layout
                for i in reversed(range(self.display_frame.layout().count())):
                    widget = self.display_frame.layout().itemAt(i).widget()
                    if widget:
                        widget.setParent(None)

                # Get the canvas object returned by displayDataInViewingWindow
                canvas = self.file_operations.displayDataInViewingWindow()

                # Add canvas to the layout of display_frame
                self.display_frame.layout().addWidget(canvas)

                print("File imported successfully:", filename)
        except Exception as e:
            print("An error occurred during file import:", e)
            QMessageBox.warning(None, "Error", f"An error occurred during file import: {str(e)}")

    def save_file(self):
        try:
            # Call the save_file method from FileOperations
            self.file_operations.save()
        except Exception as e:
            print("An error occurred during file save:", e)
            QMessageBox.warning(None, "Error", f"An error occurred during file save: {str(e)}")

    def export_file(self):
        try:
            options = QFileDialog.Options()
            options |= QFileDialog.DontUseNativeDialog
            filename, _ = QFileDialog.getSaveFileName(
                None, "Export File", "", "Supported Files (*.dt1 *.DT1 *.hd *.HD *.DZT *.dat *.GPRhdr *.rad *.rd3 *.rd7 *.gpr)", options=options)

            if filename:
                # Call the export_file method from FileOperations with the chosen filename
                self.file_operations.exportVTK(filename)
        except Exception as e:
            print("An error occurred during file export:", e)
            QMessageBox.warning(None, "Error", f"An error occurred during file export: {str(e)}")
    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.import_btn.setText(_translate("MainWindow", "Import File"))
        self.export_btn.setText(_translate("MainWindow", "Export File"))
        self.undo_tool.setText(_translate("MainWindow", "..."))
        self.redo_tool.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Set X-Range"))
        self.label_3.setText(_translate("MainWindow", "Contrast"))
        self.gridBtn.setText(_translate("MainWindow", "Grid"))
        self.label_4.setText(_translate("MainWindow", "Set Y-Range"))
        self.fviewBtn.setText(_translate("MainWindow", "Full View"))
        self.label_5.setText(_translate("MainWindow", "Aspect Ratio"))
        self.label_25.setText(_translate("MainWindow", "Min"))
        self.label_26.setText(_translate("MainWindow", "Max"))
        self.label_27.setText(_translate("MainWindow", "Max"))
        self.label_28.setText(_translate("MainWindow", "Min"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.view_ctrl), _translate("MainWindow", "View Controls"))
        self.label_7.setText(_translate("MainWindow", "Topo Correction"))
        self.label_8.setText(_translate("MainWindow", "Fk Migration"))
        self.label_9.setText(_translate("MainWindow", "Set Velocity"))
        self.antenBtn.setText(_translate("MainWindow", "Antenna Sep Correction"))
        self.traceBtn.setText(_translate("MainWindow", "Allign Traces"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.velo_ctrl), _translate("MainWindow", "Velocity Controls"))
        self.label_10.setText(_translate("MainWindow", "Adjust Profile"))
        self.label_11.setText(_translate("MainWindow", "Set Zero Time"))
        self.label_12.setText(_translate("MainWindow", "Align Traces"))
        self.label_13.setText(_translate("MainWindow", "Truncate Y"))
        self.label_14.setText(_translate("MainWindow", "Cut Profile"))
        self.label_15.setText(_translate("MainWindow", "Dewow"))
        self.label_16.setText(_translate("MainWindow", "Remove Mean Traces"))
        self.label_18.setText(_translate("MainWindow", "Profile Smoothing"))
        self.label_19.setText(_translate("MainWindow", "Tpow"))
        self.label_20.setText(_translate("MainWindow", "AGC"))
        self.label_21.setText(_translate("MainWindow", "Show hyperb"))
        self.label_29.setText(_translate("MainWindow", "x-value"))
        self.label_30.setText(_translate("MainWindow", "y-value"))
        self.label_31.setText(_translate("MainWindow", "Trace Number"))
        self.label_32.setText(_translate("MainWindow", "Copies Number"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.prof_ctrl), _translate("MainWindow", "Profile Controls"))
        self.save_tool.setText(_translate("MainWindow", "..."))
        self.refresh_tool.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Save"))
        self.start_tool.setText(_translate("MainWindow", "..."))
        self.stop_tool.setText(_translate("MainWindow", "..."))
        self.print_tool.setText(_translate("MainWindow", "..."))
        self.script_tool.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
